[package]
name = "start-minecraft-server"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "1.12.0"
signal = "0.7.0"
signal-hook = "0.3.17"
tokio = "1.37.0"

[dependencies.uuid]
version = "1.8.0"
features = [
    "v4",
    "fast-rng",
    "macro-diagnostics"
]
